### ISSUE TITLE
파이썬 전처리help

### ISSUE THREAD

**Issue by bbmini96** [2021-SMHRD-KDT-AI-1/96project#19]
list에 있는 문자열을 for문을 돌면서 int형 숫자로 변경하는방법!

**Comment by Koth100** [comment]
간단하게 해결해본 코드입니다. 실제 리스트 데이터가 이것보다 복잡하다면 데이터에 맞춰서 코드 작성해주셔야합니다
list1 = ["123","456","789"]
for i in range(len(list1)):
    list1[i] = int(list1[i])
