### ISSUE TITLE
자동차이미지help

### ISSUE THREAD

**Issue by bbmini96** [2021-SMHRD-KDT-AI-1/96project#24]
이미지 사진을 DB에 연동을 어떻게 해야하는지

**Comment by Koth100** [comment]
해당 자료 확인해보시면 좋을 것같습니다.
https://kutar37.tistory.com/entry/%EC%9B%B9%EC%97%90%EC%84%9C-%ED%8C%8C%EC%9D%BC-%EC%97%85%EB%A1%9C%EB%93%9C-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0-1

**Comment by ljlj1123** [comment]
db에 그냥 url 넣어버렸는데 이러면 안되나요>???

**Comment by Koth100** [comment]
지금단계에선 이미지가 나온다면 크게 문제는 없을것 같은데 외부 리소스를 끌어다 쓰는거라 외부 서버에 영향을 크게 받을 수 있습니다.(eg. 해당 서버가 다운상태일때는 이미지표기 불가)
