### ISSUE TITLE
크롤링에러

### ISSUE THREAD

**Issue by bbmini96** [2021-SMHRD-KDT-AI-1/96project#4]
크롤링 중에 차량목록길이만큼 while()문이 돌게 했는데 1번째 브랜드 차랑목록길이만큼만 돌아서 다른 브랜드로 이동시 에러발생했습니다

**Comment by Koth100** [comment]
1번째 브랜드 목록을 담아준 리스트 초기화가 이루어지지 않아서 발생한 문제
브랜드 마다 리스트를 초기화 시켜주도록 수정
